import images from '../assets/images';
import {
  ACRepairingIcon,
  ApplianceIcon,
  BeautyIcon,
  CleaningIcon,
  ElectronicsIcon,
  LaundryIcon,
  MassageIcon,
  MenSaloonIcon,
  MoreIcon,
  PaintingIcon,
  PlumbingIcon,
  RepairingIcon,
  ShiftingIcon,
  VehicleIcon,
} from '../assets/svgs';
import strings from '../i18n/strings';
import {StackNav} from '../navigation/NavigationKeys';

const OnBoardingSlide = [
  {
    text: 'We provide professional service at a friendly price',
    image: images.onBordingImg1,
  },
  {
    text: 'The best results and your satisfaction is our top priority',
    image: images.onBordingImg2,
  },
  {
    text: "Let's make awesome changes to your home",
    image: images.onBordingImg3,
  },
];

const GenderData = [
  {label: 'Male', value: 'male'},
  {label: 'Female', value: 'female'},
  {label: 'Other', value: 'other'},
];

const ProfileSetting = [
  {
    id: 1,
    title: strings.editProfile,
    icon: 'person-outline',
    route: StackNav.EditProfile,
    header: strings.editProfile,
  },
  {
    id: 2,
    title: strings.notification,
    icon: 'notifications-outline',
    route: StackNav.NotificationSetting,
  },
  {
    id: 3,
    title: strings.payment,
    icon: 'wallet-outline',
    route: StackNav.Payment,
  },
  {
    id: 4,
    title: strings.security,
    icon: 'shield-checkmark-outline',
    route: StackNav.Security,
  },
  {
    id: 5,
    title: strings.language,
    icon: 'options-outline',
    value: 'English(US)',
    route: StackNav.Language,
  },
  {
    id: 6,
    title: strings.darkMode,
    icon: 'contrast-outline',
    rightIcon: 'rightIcon',
  },
  {
    id: 7,
    title: strings.privacyPolicy,
    icon: 'lock-closed-outline',
    route: StackNav.PrivacyPolicy,
  },
  {
    id: 8,
    title: strings.helpCenter,
    icon: 'information-circle-outline',
    route: StackNav.HelpCenter,
  },
  {
    id: 8,
    title: "Suggestions",
    icon: 'people-outline',
    route: StackNav.Suggestions,
  },
];

const contactUsData = [
  // {
  //   id: 1,
  //   title: 'Customer Service',
  //   icon: 'headset',
  // },
  {
    id: 2,
    title: 'WhatsApp',
    icon: 'whatsapp',
  },
  {
    id: 3,
    title: 'Website',
    icon: 'google-earth',
  },
  {
    id: 4,
    title: 'Facebook',
    icon: 'facebook',
  },
  {
    id: 5,
    title: 'Instagram',
    icon: 'instagram',
  },
  {
    id: 6,
    title: 'Twitter',
    icon: 'twitter',
  },
];

const helperCategoryData = [
  'General',
  'Account',
  'Payment',
  'Subscription',
  'Others',
];

const helperData = [
  {
    title: 'What is Helpify?',
    description:
      'Anistream is a streaming service that offers a wide variety of anime titles.',
  },
  {
    title: 'How to use Helpify?',
    description:
      'You can sign up for Anistream by downloading the app from the App Store or Google Play Store.',
  },
  {
    title: 'How do I cancel a orders product?',
    description:
      'You can remove anime on your wishlist by clicking the heart icon on the anime details page.',
  },
  {
    title: 'Is Helpify free to use?',
    description:
      'You can subscribe to premium by clicking the premium button on the home page.',
  },
  {
    title: 'How to add promo on Helpify?',
    description:
      'You can download anime by clicking the download icon on the anime details page.',
  },
  {
    title: 'How to unsubscribe from premium?',
    description:
      'You can unsubscribe from premium by clicking the premium button on the home page.',
  },
];

const languageData = [
  // {
  //   title: 'Suggested',
  //   data: [{lnName: 'English(US)'}, {lnName: 'English(UK)'}],
  // },
  {
    // title: 'Language',
    data: [
      {
        lnName: 'Armenian',
      },
      {
        lnName: 'English',
      },
      {
        lnName: 'Russian',
      },
    ],
  },
];

const privacyPolicyData = [
  {
    title: strings.privacyPolicy1,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy2,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy3,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy2,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy3,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy2,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy3,
    description: strings.privacyPolicyDesc,
  },
];

const userDetail = [
  {
    name: 'Dracel Steward',
    description: 'arianacooper | 24.5M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80',
  },
  {
    name: 'John Doe',
    description: 'johndoe | 10M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1605993439219-9d09d2020fa5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzh8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Jane Smith',
    description: 'janesmith | 5M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzN8fHVzZXIlMjBwcm9maWxlJTIwd2l0aCUyMGJhY2tncm91bmR8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Bob Johnson',
    description: 'bobjohnson | 2M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dXNlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Sara Wilson',
    description: 'sarawilson | 1M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1619895862022-09114b41f16f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjJ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Tom Wilson',
    description: 'tomwilson | 500K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Alice Brown',
    description: 'alicebrown | 250K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Emily Davis',
    description: 'emilydavis | 100K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDV8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Mark Lee',
    description: 'marklee | 50K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTN8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Laura Lee',
    description: 'lauralee | 10K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1610737241336-371badac3b66?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTJ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
];

const chatData = [
  {
    id: 1,
    message: 'Hi Theresa, good morning 😄',
    time: '12:00',
    type: 'sender',
  },
  {
    id: 2,
    message: 'Hi there, good morning! How are you?',
    time: '12:01',
    type: 'receiver',
  },
  {
    id: 3,
    message: 'I am doing well, thanks for asking 😊',
    time: '12:02',
    type: 'sender',
  },
  {
    id: 4,
    message: "That's great to hear! What are your plans for the day?",
    time: '12:03',
    type: 'receiver',
  },
  {
    id: 5,
    message:
      'I have a few meetings scheduled, but otherwise just working from home. How about you?',
    time: '12:04',
    type: 'sender',
  },
  {
    id: 1,
    message: 'Hi Theresa, good morning 😄',
    time: '12:00',
    type: 'sender',
  },
  {
    id: 2,
    message: 'Hi there, good morning! How are you?',
    time: '12:01',
    type: 'receiver',
  },
  {
    id: 3,
    message: 'I am doing well, thanks for asking 😊',
    time: '12:02',
    type: 'sender',
  },
  {
    id: 4,
    message: "That's great to hear! What are your plans for the day?",
    time: '12:03',
    type: 'receiver',
  },
  {
    id: 5,
    message:
      'I have a few meetings scheduled, but otherwise just working from home. How about you?',
    time: '12:04',
    type: 'sender',
  },
  {
    id: 1,
    message: 'Hi Theresa, good morning 😄',
    time: '12:00',
    type: 'sender',
  },
  {
    id: 2,
    message: 'Hi there, good morning! How are you?',
    time: '12:01',
    type: 'receiver',
  },
  {
    id: 3,
    message: 'I am doing well, thanks for asking 😊',
    time: '12:02',
    type: 'sender',
  },
  {
    id: 4,
    message: "That's great to hear! What are your plans for the day?",
    time: '12:03',
    type: 'receiver',
  },
  {
    id: 5,
    message:
      'I have a few meetings scheduled, but otherwise just working from home. How about you?',
    time: '12:04',
    type: 'sender',
  },
];

const AddressData = [
  {
    id: 1,
    title: 'Home',
    address: '123, Main Street, New York, USA',
    isDefault: true,
  },
  {
    id: 2,
    title: 'Office',
    address: '345, Second Street, New York, USA',
    isDefault: false,
  },
  {
    id: 3,
    title: 'Appartment',
    address: '567, Third Street, New York, USA',
    isDefault: false,
  },
  {
    id: 4,
    title: "Parent's House",
    address: '789, Fourth Street, New York, USA',
    isDefault: false,
  },
  {
    id: 5,
    title: 'Farm House',
    address: '101, Fifth Street, New York, USA',
    isDefault: false,
  },
  {
    id: 6,
    title: 'Town Square',
    address: '123, Main Street, New York, USA',
    isDefault: false,
  },
  
];

const orderStatus = [
  {
    id: 1,
    title: 'Order In Transit - Dec 17',
    time: '12:00 PM',
    status: '32 Manchester Ave. Ringgold, GA 30736',
  },
  {
    id: 2,
    title: 'Order ... Customs Port - Dec 16',
    time: '14:40 PM',
    status: '4 Evergreen Street Lake Zurich, IL 60047',
  },
  {
    id: 3,
    title: 'Orders are ... Shipped - Dec 15',
    time: '11:30 AM',
    status: '9177 Hillcrest Street Wheeling, WV 26003',
  },
  {
    id: 4,
    title: 'Order is in Packing - Dec 15',
    time: '10:25 PM',
    status: '891 Glen Ridge St. Gainesville, VA 20155',
  },
  {
    id: 5,
    title: 'Verified Payments - Dec 15',
    time: '10:04 PM',
    status: '55 Summerhouse Dr. Apopka, FL 32703',
  },
];

const orderStatusCategory = [
  {
    id: 1,
    image: images.seller,
    position: 1,
    isHide: false,
  },
  {
    id: 2,
    image: images.shipping,
    position: 2,
    isHide: true,
  },
  {
    id: 3,
    image: images.courier,
    position: 3,
    isHide: true,
  },
  {
    id: 4,
    image: images.delivered,
    position: 4,
    isHide: true,
  },
];

const cleaningSampleData = [
  images.cleaningSample1,
  images.cleaningSample2,
  images.cleaningSample3,
  images.cleaningSample4,
  images.cleaningSample5,
  images.cleaningSample6,
];

const repairingSampleData = [
  images.repairingSample1,
  images.repairingSample2,
  images.repairingSample3,
  images.repairingSample4,
  images.repairingSample5,
  images.repairingSample6,
];

const paintingSampleData = [
  images.paintSample1,
  images.paintSample2,
  images.paintSample3,
  images.paintSample4,
  images.paintSample5,
  images.paintSample6,
];

const plumbingSampleData = [
  images.plumbingSample1,
  images.plumbingSample2,
  images.plumbingSample3,
  images.plumbingSample4,
  images.plumbingSample5,
  images.plumbingSample6,
];

const laundrySampleData = [
  images.laundrySample1,
  images.laundrySample2,
  images.laundrySample3,
  images.laundrySample4,
  images.laundrySample5,
  images.laundrySample6,
];

const applianceSampleData = [
  images.applianceSample1,
  images.applianceSample2,
  images.applianceSample3,
  images.applianceSample4,
  images.applianceSample5,
  images.applianceSample6,
];

const shiftingSampleData = [
  images.shiftingSample1,
  images.shiftingSample2,
  images.shiftingSample3,
  images.shiftingSample4,
  images.shiftingSample5,
  images.shiftingSample6,
];

const homeCategoryData = [
  {
    id: 1,
    image: <CleaningIcon />,
    title: strings.cleaning,
    data: [
      {
        id: 2,
        category: 'Home Cleaning',
        name: 'Emma Johnson',
        price: '$45',
        address: '789 Pine Avenue, Chicago',
        productImage: images.cleaningImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
      {
        id: 3,
        category: 'Floor Cleaning',
        name: 'Noah Thompson',
        price: '$55',
        address: '456 Elm Street, San Francisco',
        productImage: images.cleaningImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
      {
        id: 4,
        category: 'Kitchen Cleaning',
        name: 'Olivia Davis',
        price: '$35',
        address: '987 Maple Avenue, Miami',
        productImage: images.popularImg4,
        rating: '4.7',
        sold: '8,921',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
      {
        id: 5,
        category: 'Garden Cleaning',
        name: 'Liam Wilson',
        price: '$60',
        address: '654 Cedar Street, Houston',
        productImage: images.laundryImg1,
        rating: '4.3',
        sold: '5,432',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
      {
        id: 6,
        category: 'Bathroom Cleaning',
        name: 'Ava Anderson',
        price: '$50',
        address: '123 Oak Street, Los Angeles',
        productImage: images.bookmarkImg4,
        rating: '4.8',
        sold: '9,742',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
    ],
  },
  {
    id: 2,
    image: <RepairingIcon />,
    title: strings.repairing,
    data: [
      {
        id: 2,
        category: 'Appliance Repair',
        name: 'Samantha Thompson',
        price: '$58',
        address: '123 Main Street, New York',
        productImage: images.repairingImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.repairing,
        sample: repairingSampleData,
      },
      {
        id: 3,
        category: 'Electronics Repair',
        name: 'Jacob Wilson',
        price: '$72',
        address: '456 Elm Street, San Francisco',
        productImage: images.repairingImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.repairing,
        sample: repairingSampleData,
      },
      {
        id: 4,
        category: 'Computer Repair',
        name: 'Olivia Martinez',
        price: '$95',
        address: '789 Pine Avenue, Chicago',
        productImage: images.repairingImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.repairing,
        sample: repairingSampleData,
      },
      {
        id: 5,
        category: 'Car Repair',
        name: 'Ethan Anderson',
        price: '$112',
        address: '987 Maple Avenue, Miami',
        productImage: images.repairingImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.repairing,
        sample: repairingSampleData,
      },
      {
        id: 6,
        category: 'Phone Repair',
        name: 'Isabella Johnson',
        price: '$88',
        address: '654 Cedar Street, Houston',
        productImage: images.repairingImg1,
        rating: '4.8',
        sold: '9,742',
        header: strings.repairing,
        sample: repairingSampleData,
      },
    ],
  },
  {
    id: 3,
    image: <PaintingIcon />,
    title: strings.painting,
    data: [
      {
        id: 2,
        category: 'Wall Painting',
        name: 'John Smith',
        price: '250',
        unit: '1 sqm',
        address: '123 Main Street, New York',
        productImage: images.paintingImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.painting,
        sample: paintingSampleData,
      },
      {
        id: 3,
        category: 'Home Painting',
        name: 'Emily Johnson',
        price: '$320',
        address: '456 Elm Street, San Francisco',
        productImage: images.paintingImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.painting,
        sample: paintingSampleData,
      },
      {
        id: 4,
        category: 'Office Painting',
        name: 'Michael Brown',
        price: '$180',
        address: '789 Pine Avenue, Chicago',
        productImage: images.paintingImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.painting,
        sample: paintingSampleData,
      },
      {
        id: 5,
        category: 'Building Painting',
        name: 'Sophia Davis',
        price: '$290',
        address: '987 Maple Avenue, Miami',
        productImage: images.paintingImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.painting,
        sample: paintingSampleData,
      },
      {
        id: 6,
        category: 'Furniture Painting',
        name: 'William Johnson',
        price: '$200',
        address: '654 Cedar Street, Houston',
        productImage: images.paintingImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.painting,
        sample: paintingSampleData,
      },
    ],
  },
  {
    id: 4,
    image: <LaundryIcon />,
    title: strings.laundry,
    data: [
      {
        id: 2,
        category: 'Clothes Cleaning',
        name: 'Emily Wilson',
        price: '$22',
        address: '456 Elm Street, San Francisco',
        productImage: images.laundryImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.laundry,
        sample: laundrySampleData,
      },
      {
        id: 3,
        category: 'Carpet Cleaning',
        name: 'Ethan Thompson',
        price: '18',
        unit: '1 sqm',
        address: '789 Pine Avenue, Chicago',
        productImage: images.laundryImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.laundry,
        sample: laundrySampleData,
      },
      {
        id: 4,
        category: 'Laundry Men Services',
        name: 'Olivia Davis',
        price: '$30',
        address: '987 Maple Avenue, Miami',
        productImage: images.laundryImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.laundry,
        sample: laundrySampleData,
      },
      {
        id: 5,
        category: 'Laundry',
        name: 'Liam Johnson',
        price: '$26',
        address: '654 Cedar Street, Houston',
        productImage: images.laundryImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.laundry,
        sample: laundrySampleData,
      },
      {
        id: 6,
        category: 'Laundry',
        name: 'Ava Anderson',
        price: '$35',
        address: '123 Oak Street, Los Angeles',
        productImage: images.laundryImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.laundry,
        sample: laundrySampleData,
      },
    ],
  },
  {
    id: 5,
    image: <ApplianceIcon />,
    title: strings.appliance,
    data: [
      {
        id: 2,
        category: 'Household Appliance',
        name: 'Sophie Wilson',
        price: '$98',
        address: '456 Elm Street, San Francisco',
        productImage: images.applianceImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.appliance,
        sample: applianceSampleData,
      },
      {
        id: 3,
        category: 'Appliance Repair',
        name: 'Oliver Thompson',
        price: '$115',
        address: '789 Pine Avenue, Chicago',
        productImage: images.applianceImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.appliance,
        sample: applianceSampleData,
      },
      {
        id: 4,
        category: 'Appliance Repair',
        name: 'Emma Martinez',
        price: '$82',
        address: '987 Maple Avenue, Miami',
        productImage: images.applianceImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.appliance,
        sample: applianceSampleData,
      },
      {
        id: 5,
        category: 'Office Appliance',
        name: 'Liam Davis',
        price: '135',
        unit: '1 sqm',
        address: '654 Cedar Street, Houston',
        productImage: images.applianceImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.appliance,
        sample: applianceSampleData,
      },
      {
        id: 6,
        category: 'Kitchen Appliance',
        name: 'Ava Johnson',
        price: '$99',
        address: '123 Oak Street, Los Angeles',
        productImage: images.applianceImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.appliance,
        sample: applianceSampleData,
      },
    ],
  },
  {
    id: 6,
    image: <PlumbingIcon />,
    title: strings.plumbing,
    data: [
      {
        id: 2,
        category: 'Plumbing',
        name: 'Michael Johnson',
        price: '$65',
        address: '123 Main Street, New York',
        productImage: images.plumbingImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
      {
        id: 3,
        category: 'Plumbing Services',
        name: 'Emily Wilson',
        price: '$80',
        address: '456 Elm Street, San Francisco',
        productImage: images.plumbingImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
      {
        id: 4,
        category: 'Plumbing Repairing',
        name: 'Daniel Martinez',
        price: '$95',
        address: '789 Pine Avenue, Chicago',
        productImage: images.plumbingImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
      {
        id: 5,
        category: 'Plumbing Services',
        name: 'Olivia Anderson',
        price: '$72',
        address: '987 Maple Avenue, Miami',
        productImage: images.plumbingImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
      {
        id: 6,
        category: 'Household Plumbing',
        name: 'David Johnson',
        price: '$88',
        address: '654 Cedar Street, Houston',
        productImage: images.plumbingImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
    ],
  },
  {
    id: 7,
    image: <ShiftingIcon />,
    title: strings.shifting,
    data: [
      {
        id: 2,
        category: 'Domestic Shifting',
        name: 'Emily Johnson',
        price: '$350',
        address: '123 Main Street, New York',
        productImage: images.shiftingImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
      {
        id: 3,
        category: 'Goods Shifting',
        name: 'Benjamin Wilson',
        price: '$520',
        address: '456 Elm Street, San Francisco',
        productImage: images.shiftingImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
      {
        id: 4,
        category: 'Villa Shifting',
        name: 'Olivia Davis',
        price: '$450',
        address: '789 Pine Avenue, Chicago',
        productImage: images.shiftingImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
      {
        id: 5,
        category: 'Office Shifting',
        name: 'William Thompson',
        price: '$620',
        address: '987 Maple Avenue, Miami',
        productImage: images.shiftingImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
      {
        id: 6,
        category: 'House Shifting',
        name: 'Sophia Anderson',
        price: '$480',
        address: '654 Cedar Street, Houston',
        productImage: images.shiftingImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
    ],
  },
  {
    id: 8,
    image: <MoreIcon />,
    title: strings.more,
  },
];

const allServicesData = [
  {
    id: 1,
    image: <CleaningIcon />,
    title: strings.cleaning,
    data: [
      {
        id: 2,
        category: 'Home Cleaning',
        name: 'Emma Johnson',
        price: '$45',
        address: '789 Pine Avenue, Chicago',
        productImage: images.cleaningImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
      {
        id: 3,
        category: 'Floor Cleaning',
        name: 'Noah Thompson',
        price: '$55',
        address: '456 Elm Street, San Francisco',
        productImage: images.cleaningImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
      {
        id: 4,
        category: 'Kitchen Cleaning',
        name: 'Olivia Davis',
        price: '$35',
        address: '987 Maple Avenue, Miami',
        productImage: images.popularImg4,
        rating: '4.7',
        sold: '8,921',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
      {
        id: 5,
        category: 'Garden Cleaning',
        name: 'Liam Wilson',
        price: '$60',
        address: '654 Cedar Street, Houston',
        productImage: images.laundryImg1,
        rating: '4.3',
        sold: '5,432',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
      {
        id: 6,
        category: 'Bathroom Cleaning',
        name: 'Ava Anderson',
        price: '$50',
        address: '123 Oak Street, Los Angeles',
        productImage: images.bookmarkImg4,
        rating: '4.8',
        sold: '9,742',
        header: strings.cleaning,
        sample: cleaningSampleData,
      },
    ],
  },
  {
    id: 2,
    image: <RepairingIcon />,
    title: strings.repairing,
    data: [
      {
        id: 2,
        category: 'Appliance Repair',
        name: 'Samantha Thompson',
        price: '$58',
        address: '123 Main Street, New York',
        productImage: images.repairingImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.repairing,
        sample: repairingSampleData,
      },
      {
        id: 3,
        category: 'Electronics Repair',
        name: 'Jacob Wilson',
        price: '$72',
        address: '456 Elm Street, San Francisco',
        productImage: images.repairingImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.repairing,
        sample: repairingSampleData,
      },
      {
        id: 4,
        category: 'Computer Repair',
        name: 'Olivia Martinez',
        price: '$95',
        address: '789 Pine Avenue, Chicago',
        productImage: images.repairingImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.repairing,
        sample: repairingSampleData,
      },
      {
        id: 5,
        category: 'Car Repair',
        name: 'Ethan Anderson',
        price: '$112',
        address: '987 Maple Avenue, Miami',
        productImage: images.repairingImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.repairing,
        sample: repairingSampleData,
      },
      {
        id: 6,
        category: 'Phone Repair',
        name: 'Isabella Johnson',
        price: '$88',
        address: '654 Cedar Street, Houston',
        productImage: images.repairingImg1,
        rating: '4.8',
        sold: '9,742',
        header: strings.repairing,
        sample: repairingSampleData,
      },
    ],
  },
  {
    id: 3,
    image: <PaintingIcon />,
    title: strings.painting,
    data: [
      {
        id: 2,
        category: 'Wall Painting',
        name: 'John Smith',
        price: '250',
        unit: '1 sqm',
        address: '123 Main Street, New York',
        productImage: images.paintingImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.painting,
        sample: paintingSampleData,
      },
      {
        id: 3,
        category: 'Home Painting',
        name: 'Emily Johnson',
        price: '$320',
        address: '456 Elm Street, San Francisco',
        productImage: images.paintingImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.painting,
        sample: paintingSampleData,
      },
      {
        id: 4,
        category: 'Office Painting',
        name: 'Michael Brown',
        price: '$180',
        address: '789 Pine Avenue, Chicago',
        productImage: images.paintingImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.painting,
        sample: paintingSampleData,
      },
      {
        id: 5,
        category: 'Building Painting',
        name: 'Sophia Davis',
        price: '$290',
        address: '987 Maple Avenue, Miami',
        productImage: images.paintingImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.painting,
        sample: paintingSampleData,
      },
      {
        id: 6,
        category: 'Furniture Painting',
        name: 'William Johnson',
        price: '$200',
        address: '654 Cedar Street, Houston',
        productImage: images.paintingImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.painting,
        sample: paintingSampleData,
      },
    ],
  },
  {
    id: 4,
    image: <LaundryIcon />,
    title: strings.laundry,
    data: [
      {
        id: 2,
        category: 'Clothes Cleaning',
        name: 'Emily Wilson',
        price: '$22',
        address: '456 Elm Street, San Francisco',
        productImage: images.laundryImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.laundry,
        sample: laundrySampleData,
      },
      {
        id: 3,
        category: 'Carpet Cleaning',
        name: 'Ethan Thompson',
        price: '250',
        unit: '1 sqm',
        address: '789 Pine Avenue, Chicago',
        productImage: images.laundryImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.laundry,
        sample: laundrySampleData,
      },
      {
        id: 4,
        category: 'Laundry Men Services',
        name: 'Olivia Davis',
        price: '$30',
        address: '987 Maple Avenue, Miami',
        productImage: images.laundryImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.laundry,
        sample: laundrySampleData,
      },
      {
        id: 5,
        category: 'Laundry',
        name: 'Liam Johnson',
        price: '$26',
        address: '654 Cedar Street, Houston',
        productImage: images.laundryImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.laundry,
        sample: laundrySampleData,
      },
      {
        id: 6,
        category: 'Laundry',
        name: 'Ava Anderson',
        price: '$35',
        address: '123 Oak Street, Los Angeles',
        productImage: images.laundryImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.laundry,
        sample: laundrySampleData,
      },
    ],
  },
  {
    id: 5,
    image: <ApplianceIcon />,
    title: strings.appliance,
    data: [
      {
        id: 2,
        category: 'Household Appliance',
        name: 'Sophie Wilson',
        price: '$98',
        address: '456 Elm Street, San Francisco',
        productImage: images.applianceImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.appliance,
        sample: applianceSampleData,
      },
      {
        id: 3,
        category: 'Appliance Repair',
        name: 'Oliver Thompson',
        price: '$115',
        address: '789 Pine Avenue, Chicago',
        productImage: images.applianceImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.appliance,
        sample: applianceSampleData,
      },
      {
        id: 4,
        category: 'Appliance Repair',
        name: 'Emma Martinez',
        price: '$82',
        address: '987 Maple Avenue, Miami',
        productImage: images.applianceImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.appliance,
        sample: applianceSampleData,
      },
      {
        id: 5,
        category: 'Office Appliance',
        name: 'Liam Davis',
        price: '250',
        unit: '1 sqm',
        address: '654 Cedar Street, Houston',
        productImage: images.applianceImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.appliance,
        sample: applianceSampleData,
      },
      {
        id: 6,
        category: 'Kitchen Appliance',
        name: 'Ava Johnson',
        price: '$99',
        address: '123 Oak Street, Los Angeles',
        productImage: images.applianceImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.appliance,
        sample: applianceSampleData,
      },
    ],
  },
  {
    id: 6,
    image: <PlumbingIcon />,
    title: strings.plumbing,
    data: [
      {
        id: 2,
        category: 'Plumbing',
        name: 'Michael Johnson',
        price: '$65',
        address: '123 Main Street, New York',
        productImage: images.plumbingImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
      {
        id: 3,
        category: 'Plumbing Services',
        name: 'Emily Wilson',
        price: '$80',
        address: '456 Elm Street, San Francisco',
        productImage: images.plumbingImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
      {
        id: 4,
        category: 'Plumbing Repairing',
        name: 'Daniel Martinez',
        price: '$95',
        address: '789 Pine Avenue, Chicago',
        productImage: images.plumbingImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
      {
        id: 5,
        category: 'Plumbing Services',
        name: 'Olivia Anderson',
        price: '$72',
        address: '987 Maple Avenue, Miami',
        productImage: images.plumbingImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
      {
        id: 6,
        category: 'Household Plumbing',
        name: 'David Johnson',
        price: '$88',
        address: '654 Cedar Street, Houston',
        productImage: images.plumbingImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.plumbing,
        sample: plumbingSampleData,
      },
    ],
  },
  {
    id: 7,
    image: <ShiftingIcon />,
    title: strings.shifting,
    data: [
      {
        id: 2,
        category: 'Domestic Shifting',
        name: 'Emily Johnson',
        price: '$350',
        address: '123 Main Street, New York',
        productImage: images.shiftingImg1,
        rating: '4.5',
        sold: '6,842',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
      {
        id: 3,
        category: 'Goods Shifting',
        name: 'Benjamin Wilson',
        price: '$520',
        address: '456 Elm Street, San Francisco',
        productImage: images.shiftingImg2,
        rating: '4.2',
        sold: '3,256',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
      {
        id: 4,
        category: 'Villa Shifting',
        name: 'Olivia Davis',
        price: '$450',
        address: '789 Pine Avenue, Chicago',
        productImage: images.shiftingImg3,
        rating: '4.7',
        sold: '8,921',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
      {
        id: 5,
        category: 'Office Shifting',
        name: 'William Thompson',
        price: '$620',
        address: '987 Maple Avenue, Miami',
        productImage: images.shiftingImg4,
        rating: '4.3',
        sold: '5,432',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
      {
        id: 6,
        category: 'House Shifting',
        name: 'Sophia Anderson',
        price: '$480',
        address: '654 Cedar Street, Houston',
        productImage: images.shiftingImg5,
        rating: '4.8',
        sold: '9,742',
        header: strings.shifting,
        sample: shiftingSampleData,
      },
    ],
  },
  {
    id: 8,
    image: <BeautyIcon />,
    title: strings.Beauty,
    data: [
      {
        id: 2,
        category: 'Haircut',
        name: 'Lily Anderson',
        price: '$28',
        address: '123 Main Street, New York',
        productImage: images.bookmarkImg3,
        rating: '4.5',
        sold: '6,842',
        header: strings.Beauty,
      },
      {
        id: 3,
        category: 'Makeup',
        name: 'Sophia Thompson',
        price: '$35',
        address: '456 Elm Street, San Francisco',
        productImage: images.popularImg6,
        rating: '4.2',
        sold: '3,256',
        header: strings.Beauty,
      },
    ],
  },
  {
    id: 9,
    image: <ACRepairingIcon />,
    title: strings.acRepair,
    data: [
      {
        id: 2,
        category: 'AC Repairing',
        name: 'Sophia Anderson',
        price: '$65',
        address: '789 Pine Avenue, Chicago',
        productImage: images.applianceImg3,
        rating: '4.5',
        sold: '6,842',
        header: strings.acRepair,
      },
      {
        id: 3,
        category: 'AC Repairing',
        name: 'Liam Wilson',
        price: '$80',
        address: '456 Elm Street, San Francisco',
        productImage: images.applianceImg5,
        rating: '4.2',
        sold: '3,256',
        header: strings.acRepair,
      },
      {
        id: 4,
        category: 'AC Repairing',
        name: 'Ava Davis',
        price: '$55',
        address: '987 Maple Avenue, Miami',
        productImage: images.applianceImg1,
        rating: '4.7',
        sold: '8,921',
        header: strings.acRepair,
      },
    ],
  },
  {
    id: 10,
    image: <VehicleIcon />,
    title: strings.vehicle,
    data: [
      {
        id: 2,
        category: 'Vehicle Repairing',
        name: 'John Smith',
        price: '$650',
        address: '123 Main Street, New York',
        productImage: images.applianceImg2,
        rating: '4.5',
        sold: '6,842',
        header: strings.vehicle,
      },
      {
        id: 3,
        category: 'Motorcycle Modification',
        name: 'Emily Johnson',
        price: '$450',
        address: '456 Elm Street, San Francisco',
        productImage: images.applianceImg5,
        rating: '4.2',
        sold: '3,256',
        header: strings.vehicle,
      },
    ],
  },
  {
    id: 11,
    image: <ElectronicsIcon />,
    title: strings.electronics,
    data: [
      {
        id: 2,
        category: 'Electronics',
        name: 'Elijah Miller',
        price: '$420',
        address: '123 Main Street, New York',
        productImage: images.applianceImg5,
        rating: '4.6',
        sold: '6,842',
        header: strings.electronics,
      },
      {
        id: 3,
        category: 'Electronics',
        name: 'Sophia Adams',
        price: '$580',
        address: '456 Elm Street, San Francisco',
        productImage: images.popularImg8,
        rating: '4.8',
        sold: '3,256',
        header: strings.electronics,
      },
      {
        id: 4,
        category: 'Electronics',
        name: 'Oliver Carter',
        price: '$690',
        address: '789 Pine Avenue, Chicago',
        productImage: images.popularImg3,
        rating: '4.4',
        sold: '8,921',
        header: strings.electronics,
      },
      {
        id: 5,
        category: 'Electronics',
        name: 'Ava Foster',
        price: '$520',
        address: '987 Maple Avenue, Miami',
        productImage: images.bookmarkImg3,
        rating: '4.7',
        sold: '5,432',
        header: strings.electronics,
      },
      {
        id: 6,
        category: 'Electronics',
        name: 'Mason Simmons',
        price: '$450',
        address: '654 Cedar Street, Houston',
        productImage: images.bookmarkImg1,
        rating: '4.5',
        sold: '9,742',
        header: strings.electronics,
      },
    ],
  },
  {
    id: 12,
    image: <MassageIcon />,
    title: strings.massage,
    data: [
      {
        id: 2,
        category: 'Massage',
        name: 'Emily Johnson',
        price: '$65',
        address: '123 Main Street, New York',
        productImage: images.popularImg4,
        rating: '4.5',
        sold: '6,842',
        header: strings.massage,
      },
      {
        id: 3,
        category: 'Massage',
        name: 'Liam Wilson',
        price: '$80',
        address: '456 Elm Street, San Francisco',
        productImage: images.bookmarkImg3,
        rating: '4.2',
        sold: '3,256',
        header: strings.massage,
      },
    ],
  },
  {
    id: 13,
    image: <MenSaloonIcon />,
    title: strings.menSalon,
    data: [
      {
        id: 5,
        category: "Men's Salon",
        name: 'David Anderson',
        price: '$30',
        address: '987 Maple Avenue, Miami',
        productImage: images.paintingImg3,
        rating: '4.3',
        sold: '5,432',
        header: strings.menSalon,
      },
      {
        id: 6,
        category: "Men's Salon",
        name: 'Andrew Thompson',
        price: '$38',
        address: '654 Cedar Street, Houston',
        productImage: images.plumbingImg4,
        rating: '4.8',
        sold: '9,742',
        header: strings.menSalon,
      },
    ],
  },
];

const mostPopularData = [
  strings.all,
  strings.cleaning,
  strings.painting,
  strings.laundry,
  strings.appliance,
  strings.plumbing,
  strings.shifting,
  strings.repairing,
  strings.massage,
];

const homeProductData = [
  {
    id: 2,
    category: 'Wall Painting',
    name: 'John Smith',
    price: '250',
    unit: '1 sqm',
    address: '123 Main Street, New York',
    productImage: images.paintingImg1,
    rating: '4.5',
    sold: '6,842',
    header: strings.painting,
    sample: paintingSampleData,
  },
  {
    id: 3,
    category: 'Carpet Cleaning',
    name: 'Ethan Thompson',
    price: '250',
    unit: '1 sqm',
    address: '789 Pine Avenue, Chicago',
    productImage: images.laundryImg2,
    rating: '4.2',
    sold: '3,256',
    header: strings.laundry,
    sample: laundrySampleData,
  },
  {
    id: 5,
    category: 'Office Appliance',
    name: 'Liam Davis',
    price: '250',
    unit: '1 sqm',
    address: '654 Cedar Street, Houston',
    productImage: images.applianceImg4,
    rating: '4.3',
    sold: '5,432',
    header: strings.appliance,
    sample: applianceSampleData,
  },
  {
    id: 6,
    category: 'Plumbing Services',
    name: 'Olivia Anderson',
    price: '$72',
    address: '987 Maple Avenue, Miami',
    productImage: images.plumbingImg4,
    rating: '4.3',
    sold: '5,432',
    header: strings.plumbing,
    sample: plumbingSampleData,
  },
  {
    id: 4,
    category: 'Villa Shifting',
    name: 'Olivia Davis',
    price: '$450',
    address: '789 Pine Avenue, Chicago',
    productImage: images.shiftingImg3,
    rating: '4.7',
    sold: '8,921',
    header: strings.shifting,
    sample: shiftingSampleData,
  },
  {
    id: 2,
    category: 'Haircut',
    name: 'Lily Anderson',
    price: '$28',
    address: '123 Main Street, New York',
    productImage: images.bookmarkImg3,
    rating: '4.5',
    sold: '6,842',
    header: strings.massage,
    sample: applianceSampleData,
  },
  {
    id: 3,
    category: 'AC Repairing',
    name: 'Liam Wilson',
    price: '$80',
    address: '456 Elm Street, San Francisco',
    productImage: images.applianceImg5,
    rating: '4.2',
    sold: '3,256',
    header: strings.repairing,
    sample: repairingSampleData,
  },
];

const notificationData = [
  {
    title: 'Today',
    data: [
      {
        id: 1,
        image: images.notificationImage1,
        title: '30% Special Discount!',
        description: 'Special promotion only valid today',
      },
    ],
  },
  {
    title: 'Yesterday',
    data: [
      {
        id: 1,
        image: images.notificationImage2,
        title: 'Top Up E-Wallet Successful!',
        description: 'You have to top up your e-wallet',
      },
      {
        id: 1,
        image: images.notificationImage3,
        title: 'New Services Available!',
        description: 'Now you can track orders in real time',
      },
    ],
  },
  {
    title: 'December 22, 2024',
    data: [
      {
        id: 1,
        image: images.notificationImage1,
        title: 'Credit Card Connected!',
        description: 'Credit Card has been linked!',
      },
      {
        id: 1,
        image: images.notificationImage4,
        title: 'Account Setup Successful!',
        description: 'Your account has been created!',
      },
    ],
  },
];

const ratingData = [strings.all, '5', '4', '3', '2', '1'];

const timeData = ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM'];

const reviewsData = [
  {
    id: 1,
    name: 'John Duew',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',

    rating: 5,
    review:
      'The item is very good, my son likes it very much and plays every day 💯💯💯',
    like: 352,
    time: '6 days ago',
  },
  {
    id: 2,
    name: 'Jane Doe',
    image: 'https://randomuser.me/api/portraits/women/1.jpg',

    rating: 4,
    review:
      'The item is good, but it could be better. My son likes it, but he has some complaints about it.',
    like: 100,
    time: '2 days ago',
  },
  {
    id: 3,
    name: 'Bob Smith',
    image: 'https://randomuser.me/api/portraits/men/2.jpg',

    rating: 3,
    review:
      'The item is okay, but it could be better. My son likes it, but he has some complaints about it.',
    like: 50,
    time: '1 day ago',
  },
  {
    id: 4,
    name: 'Alice Johnson',
    image: 'https://randomuser.me/api/portraits/women/2.jpg',

    rating: 2,
    review:
      'The item is not very good. My son does not like it very much and does not play with it often.',
    like: 10,
    time: '1 hour ago',
  },
  {
    id: 5,
    name: 'Tom Hanks',
    image: 'https://randomuser.me/api/portraits/men/3.jpg',

    rating: 1,
    review:
      'The item is terrible. My son hates it and does not play with it at all.',
    like: 1,
    time: '1 minute ago',
  },
  {
    id: 6,
    name: 'Megan Fox',
    image: 'https://randomuser.me/api/portraits/women/3.jpg',

    rating: 5,
    review:
      'The item is very good, my son likes it very much and plays every day 💯💯💯',
    like: 352,
    time: '6 days ago',
  },
  {
    id: 7,
    name: 'Samantha Smith',
    image: 'https://randomuser.me/api/portraits/women/4.jpg',

    rating: 4,
    review:
      'The item is good, but it could be better. My daughter likes it, but she has some complaints about it.',
    like: 200,
    time: '3 days ago',
  },
  {
    id: 8,
    name: 'David Johnson',
    image: 'https://randomuser.me/api/portraits/men/4.jpg',

    rating: 3,
    review:
      'The item is okay, but it could be better. My daughter likes it, but she has some complaints about it.',
    like: 100,
    time: '2 days ago',
  },
  {
    id: 9,
    name: 'Emily Brown',
    image: 'https://randomuser.me/api/portraits/women/5.jpg',

    rating: 2,
    review:
      'The item is not very good. My daughter does not like it very much and does not play with it often.',
    like: 20,
    time: '1 day ago',
  },
  {
    id: 10,
    name: 'Olivia Davis',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',

    rating: 1,
    review:
      'The item is terrible. My daughter hates it and does not play with it at all.',
    like: 2,
    time: '1 hour ago',
  },
  {
    id: 11,
    name: 'Sophia Wilson',
    image: 'https://randomuser.me/api/portraits/women/7.jpg',

    rating: 5,
    review:
      'The item is very good, my daughter likes it very much and plays every day 💯💯💯',
    like: 352,
    time: '6 days ago',
  },
];

const sortAndFilterData = [
  strings.mostPopular,
  strings.mostRecent,
  strings.oldest,
  strings.priceLowToHigh,
  strings.priceHighToLow,
];

const shippingData = [
  {
    id: 1,
    title: 'Economy',
    description: 'Delivery in 3-5 days',
    price: '$10',
    image: images.shipping1,
  },
  {
    id: 2,
    title: 'Regular',
    description: 'Delivery in 2-3 days',
    price: '$15',
    image: images.seller,
  },
  {
    id: 3,
    title: 'Cargo',
    description: 'Delivery in 1-2 days',
    price: '$20',
    image: images.shipping,
  },
  {
    id: 3,
    title: 'Express',
    description: 'Delivery in 1 days',
    price: '$25',
    image: images.shipping2,
  },
];

const addPromoData = [
  {
    id: 1,
    title: 'Special 25% Off',
    description: 'Special promo only today!',
  },
  {
    id: 2,
    title: 'Discount 30% Off',
    description: 'New user special promo',
  },
  {
    id: 3,
    title: 'Special 20% Off',
    description: 'Special promo only today!',
  },
  {
    id: 4,
    title: 'Discount 15% Off',
    description: 'Special promo only valid today!',
  },
  {
    id: 5,
    title: 'Discount 35% Off',
    description: 'Special promo only valid today!',
  },
];

const inboxChatData = [
  {
    id: 1,
    store: 'John Doe',
    message: 'Hello, welcome to BMW ...',
    time: '09.41',
    notification: 2,
    image:
      'https://images.unsplash.com/photo-1605993439219-9d09d2020fa5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzh8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 2,
    store: 'Jane Smith',
    message: 'I just completed it 😂😂',
    time: '09:22',
    notification: 4,
    image:
      'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dXNlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 3,
    store: 'Mark Johnson',
    message: 'omg, this is amazing 🔥🔥🔥',
    time: '09.16',
    image:
      'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 4,
    store: 'Sarah Brown',
    message: 'Wow, this is really fast 😎',
    time: 'Yesterday',
    notification: 2,
    image:
      'https://images.unsplash.com/photo-1619895862022-09114b41f16f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjJ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 5,
    store: 'Emily Johnson',
    message: 'just ideas for next time 😆',
    time: 'Dec 20, 2024',
    notification: 1,
    image:
      'https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzN8fHVzZXIlMjBwcm9maWxlJTIwd2l0aCUyMGJhY2tncm91bmR8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 6,
    store: 'Alex Thompson',
    message: "I'm really like driving! 😄😄",
    time: 'Dec 20, 2024',
    image:
      'https://images.unsplash.com/photo-1605993439219-9d09d2020fa5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzh8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 7,
    store: 'Ryan Wilson',
    message: 'perfect! 💯💯💯',
    time: 'Dec 20, 2024',
    image:
      'https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80',
  },
  {
    id: 9,
    store: 'Chris Adams',
    message: 'I just completed it 😂😂',
    time: '20.00',
    image:
      'https://images.unsplash.com/photo-1610737241336-371badac3b66?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTJ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
];

const inboxCallData = [
  {
    id: 1,
    store: 'Emily Thompson',
    time: 'Nov 28, 2024',
    status: strings.outgoing,
    image:
      'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDV8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 2,
    store: 'William Johnson',
    time: 'Nov 28, 2024',
    status: strings.incoming,
    image:
      'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDV8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 3,
    store: 'Sophia Davis',
    time: 'Dec 20, 2024',
    status: strings.incoming,
    image:
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTN8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 4,
    store: 'Benjamin Wilson',
    time: 'Oct 30, 2024',
    status: strings.outgoing,
    image:
      'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDV8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 5,
    store: 'Olivia Thompson',
    time: 'Dec 17, 2024',
    status: strings.outgoing,
    image:
      'https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 6,
    store: 'Lucas Anderson',
    time: 'Dec 19, 2024',
    status: strings.incoming,
    image:
      'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 7,
    store: 'Harper Thompson',
    time: 'Nov 28, 2024',
    status: strings.outgoing,
    image:
      'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDV8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 9,
    store: 'Ethan Davis',
    time: 'Nov 28, 2024',
    status: strings.incoming,
    image:
      'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDV8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
];

const upcomingData = [
  {
    id: 2,
    category: 'Home Cleaning',
    name: 'Emma Johnson',
    price: '$45',
    address: '789 Pine Avenue, Chicago',
    productImage: images.cleaningImg1,
    rating: '4.5',
    sold: '6,842',
    header: strings.cleaning,
    sample: cleaningSampleData,
    time: 'Sat, Jun 15 • 11.00 - 13.00 AM',
  },
  {
    id: 3,
    category: 'Carpet Cleaning',
    name: 'Ethan Thompson',
    price: '250',
    unit: '1 sqm',
    address: '789 Pine Avenue, Chicago',
    productImage: images.laundryImg2,
    rating: '4.2',
    sold: '3,256',
    header: strings.laundry,
    sample: laundrySampleData,
    time: 'Sat, Jun 15 • 11.00 - 13.00 AM',
  },
  {
    id: 4,
    category: 'Office Painting',
    name: 'Michael Brown',
    price: '$180',
    address: '789 Pine Avenue, Chicago',
    productImage: images.paintingImg3,
    rating: '4.7',
    sold: '8,921',
    header: strings.painting,
    sample: paintingSampleData,
    time: 'Sun, Jul 12 • 15.00 - 17.00 PM',
  },
  {
    id: 6,
    category: 'Bathroom Cleaning',
    name: 'Ava Anderson',
    price: '$50',
    address: '123 Oak Street, Los Angeles',
    productImage: images.bookmarkImg4,
    rating: '4.8',
    sold: '9,742',
    header: strings.cleaning,
    sample: cleaningSampleData,
    time: 'Sun, Jul 12 • 15.00 - 17.00 PM',
  },
];

const cancelData = [
  {
    id: 1,
    category: 'Floor Cleaning',
    name: 'Noah Thompson',
    price: '$55',
    address: '456 Elm Street, San Francisco',
    productImage: images.cleaningImg2,
    rating: '4.2',
    sold: '3,256',
    header: strings.cleaning,
    sample: cleaningSampleData,
    time: 'Sat, May 7 • 11.00 - 13.00 AM',
  },
  {
    id: 2,
    category: 'Haircut',
    name: 'Lily Anderson',
    price: '$28',
    address: '123 Main Street, New York',
    productImage: images.bookmarkImg3,
    rating: '4.5',
    sold: '6,842',
    header: strings.massage,
    sample: applianceSampleData,
    time: 'Sat, May 7 • 11.00 - 13.00 AM',
  },
  {
    id: 5,
    category: 'Laundry',
    name: 'Liam Johnson',
    price: '$26',
    address: '654 Cedar Street, Houston',
    productImage: images.laundryImg4,
    rating: '4.3',
    sold: '5,432',
    header: strings.laundry,
    sample: laundrySampleData,
    time: 'Sun, Jun 13 • 15.00 - 17.00 PM',
  },
  {
    id: 3,
    category: 'Appliance Repair',
    name: 'Oliver Thompson',
    price: '$115',
    address: '789 Pine Avenue, Chicago',
    productImage: images.applianceImg2,
    rating: '4.2',
    sold: '3,256',
    header: strings.appliance,
    sample: applianceSampleData,
    time: 'Sun, Jun 13 • 15.00 - 17.00 PM',
  },
  {
    id: 4,
    category: 'Goods Shifting',
    name: 'Benjamin Wilson',
    price: '$520',
    address: '456 Elm Street, San Francisco',
    productImage: images.shiftingImg2,
    rating: '4.2',
    sold: '3,256',
    header: strings.shifting,
    sample: shiftingSampleData,
    time: 'Sun, Jun 13 • 15.00 - 17.00 PM',
  },
];

const bookedData = [
  {
    id: 4,
    category: 'Plumbing Repairing',
    name: 'Daniel Martinez',
    price: '$95',
    address: '789 Pine Avenue, Chicago',
    productImage: images.plumbingImg3,
    rating: '4.7',
    sold: '8,921',
    header: strings.plumbing,
    sample: plumbingSampleData,
    time: 'Sat, May 7 • 11.00 - 13.00 AM',
  },
  {
    id: 6,
    category: 'Bathroom Cleaning',
    name: 'Ava Anderson',
    price: '$50',
    address: '123 Oak Street, Los Angeles',
    productImage: images.bookmarkImg4,
    rating: '4.8',
    sold: '9,742',
    header: strings.cleaning,
    sample: cleaningSampleData,
    time: 'Sat, May 7 • 11.00 - 13.00 AM',
  },
];

const houseCleaningData = [
  'Living Room',
  'Bedroom',
  'Kitchen',
  'Bathroom',
  'Balcony',
  'Garage',
  'Basement',
  'Office',
  'Other',
];

const shiftingData = [
  'Table',
  'Chair',
  'Sofa',
  'Bed',
  'Wardrobe',
  'Dressing Table',
  'TV',
  'Fridge',
  'Washing Machine',
  'Air Conditioner',
  'Other',
];

const carBrandData = [
  'Audi',
  'BMW',
  'Chevrolet',
  'Ford',
  'Honda',
  'Hyundai',
  'Kia',
  'Mercedes-Benz',
  'Nissan',
  'Toyota',
].map(brand => ({label: brand, value: brand}));

const carModelData = [
  'A3',
  'Seltos',
  'Sonet',
  'Creta',
  'Carnival',
  'Bolero',
  'XUV300',
  'XUV500',
  'Scorpio',
  'Thar',
].map(model => ({label: model, value: model}));

const yesNoData = [
  {label: 'Yes', value: 'Yes'},
  {label: 'No', value: 'No'},
];

const applianceData = [
  'Washing Machine',
  'Refrigerator',
  'Air Conditioner',
  'Microwave Oven',
  'Water Purifier',
  'Television',
  'Grilling Machine',
];

const houseSizeData = ['Small', 'Medium', 'Large', 'Extra Large'].map(
  model => ({label: model, value: model}),
);

const colorData = [
  '#f0f0f0',
  '#000',
  '#808080',
  '#800000',
  '#808000',
  '#008000',
  '#800080',
  '#008080',
  '#000080',
  '#ff0000',
  '#ffff00',
  '#00ff00',
  '#ff00ff',
  '#00ffff',
  '#0000ff',
  '#c0c0c0',
  '#808080',
  '#9999ff',
  '#993366',
  '#ffffcc',
  '#ccffff',
  '#660066',
  '#ff8080',
  '#0066cc',
  '#ccccff',
  '#000080',
  '#ff00ff',
  '#ffff00',
  '#00ffff',
  '#800080',
  '#800000',
  '#008080',
  '#0000ff',
  '#00ccff',
  '#ccffff',
  '#ccffcc',
  '#ffff99',
  '#99ccff',
  '#ff99cc',
  '#cc99ff',
  '#ffcc99',
  '#3366ff',
  '#33cccc',
  '#99cc00',
  '#ffcc00',
  '#ff9900',
  '#ff6600',
  '#666699',
  '#969696',
  '#003366',
  '#339966',
  '#003300',
  '#333300',
  '#993300',
  '#993366',
  '#333399',
  '#333333',
];

const countryData = [
  {label: 'India', value: 'India'},
  {label: 'USA', value: 'USA'},
  {label: 'UK', value: 'UK'},
  {label: 'Canada', value: 'Canada'},
  {label: 'Australia', value: 'Australia'},
  {label: 'New Zealand', value: 'New Zealand'},
  {label: 'South Africa', value: 'South Africa'},
];

export {
  ProfileSetting,
  GenderData,
  OnBoardingSlide,
  contactUsData,
  helperCategoryData,
  helperData,
  languageData,
  privacyPolicyData,
  userDetail,
  chatData,
  AddressData,
  orderStatus,
  orderStatusCategory,
  homeCategoryData,
  allServicesData,
  mostPopularData,
  homeProductData,
  notificationData,
  ratingData,
  timeData,
  reviewsData,
  sortAndFilterData,
  shippingData,
  addPromoData,
  cleaningSampleData,
  repairingSampleData,
  paintingSampleData,
  plumbingSampleData,
  laundrySampleData,
  applianceSampleData,
  shiftingSampleData,
  inboxCallData,
  inboxChatData,
  upcomingData,
  cancelData,
  bookedData,
  houseCleaningData,
  carBrandData,
  carModelData,
  yesNoData,
  applianceData,
  houseSizeData,
  colorData,
  shiftingData,
  countryData,
};
