export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_USER_INFO_NAME = 'CHANGE_USER_INFO_NAME';
export const CHANGE_MOST_POPULAR_CATEGORY = 'CHANGE_MOST_POPULAR_CATEGORY';
